### ISSUE TITLE
Customized ssh key fingerprinter

### ISSUE THREAD

**Issue by chunfengyao** [fffaraz/fakessh#2]
Is there any way to customize the ssh key fingerprinter(load key-pairs from local file)?

**Comment by chunfengyao** [comment]
My host has been under attack for a long time. I want to determine whether the hacker is using a password dictionary. So, I redirected the host's SSH port to FakeSSH (running in a Docker container). However, the fingerprint provided by FakeSSH is different from that of the host machine.

**Comment by ChengShusss** [comment]
Change `rand.Reader` to your private key in fakessh.go:50 should be work
